# hosts-dev 
---
webservers:
  hosts:
    host1:
      ansible_host: 192.168.3.216
      host_name: app1
    host2:
      ansible_host: 192.168.3.207
      host_name: app2
    vars:
      ansible_connection: ssh
      ansible_user: user
      ansible_ssh_pass: user
      
