---
hosts:
  app1: 
  app2:
ansible_hosts:  
    192.168.3.216
    192.168.3.207
#  vars:
 #   private_key_file: ../ssh/id_rsa
  #  host_key_checking: false
   # ansible_connection: ssh
    #ansible_user: user
    #ansible_ssh_pass: user
     


# hosts-dev 

#[webservers]
#app1 ansible_host=192.168.3.216
#app2 ansible_host=192.168.3.207

#[local]
#control ansible_connection=local

#[all:vars]
#ansible_connection=ssh
#ansible_user=user
#ansible_ssh_pass=user
