# setup-app.yml

---
  - hosts: webservers
    become: true

    vars: 
      path_to_app: "/var/www/html "

    tasks:
      - name: upload app file
        copy:
          src: ../index.php
          dest: {{path_to_app}}
          mode: 0755

      - name: create simple info page
        copy: 
          dest: "{{path_to_app}}/info.php"
          content: "<h1> info about our webserver {{ansible_hostname}}</h1> "
    