# setup-app.yml

---
  - hosts: webservers
    become: true
    tasks:
      - name: upload app file
        copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0755
      - name: supprimer le mauvais doc
        file:
          state: absent
          path: "/var/wwwhtml"