---

- hosts: local

  tasks:
    - name: Check global ports
      wait_for:
        host: "{{ item.ansible_host }}"
        port: "22"
        state: started         # Port should be open
        delay: 0               # No wait before first check (sec)
        timeout: 3             # Stop checking after timeout (sec)
      ignore_errors: yes
      with_items: "{{ hosts }}"
